CREATE TABLE [CDM].[CustomerAccounts] (
    [CustomerAccountID]             INT             IDENTITY (1, 1) NOT NULL,
    [CustomerAccountCK]             VARCHAR (100)   NULL,
    [SourceSystemName]              VARCHAR (6)     NULL,
    [IsActive]                      BIT             NULL,
    [SourceSystemID]                INT             NULL,
    [CustomerAccountOrganizationID] INT             NULL,
    [Status]                        BIT             NULL,
    [CustomerNumber]                VARCHAR (30)    NULL,
    [AccountName1]                  VARCHAR (70)    NULL,
    [AccountName2]                  VARCHAR (70)    NULL,
    [SearchTerm]                    CHAR (20)       NULL,
    [ConditionGroup]                CHAR (2)        NULL,
    [Req8130AirWorthinessCert]      BIT             NULL,
    [Req106materialCert]            BIT             NULL,
    [RegFAAmaterialCert]            BIT             NULL,
    [ReqFAAqualityCert]             BIT             NULL,
    [ReqMfrCert]                    VARCHAR (1)     NULL,
    [RegBeCert]                     VARCHAR (1)     NULL,
    [OrderBlockFlag]                VARCHAR (2)     NULL,
    [OrderMinimum]                  VARCHAR (10)    NULL,
    [LineMinimum]                   VARCHAR (3)     NULL,
    [CompanyCode]                   VARCHAR (4)     NULL,
    [CustomerType]                  VARCHAR (10)    NULL,
    [IsHoldBillFlag]                BIT             NULL,
    [PriceListID]                   INT             NULL,
    [SalesChannelCode]              VARCHAR (10)    NULL,
    [IsShipSetsIncludelinesFlag]    BIT             NULL,
    [PartyID]                       INT             NULL,
    [PartyNumber]                   INT             NULL,
    [PartyName]                     VARCHAR (255)   NULL,
    [PartyType]                     VARCHAR (10)    NULL,
    [PartyOrigSystemReference]      VARCHAR (10)    NULL,
    [WebEnabled]                    VARCHAR (3)     NULL,
    [CEHFlag]                       BIT             NULL,
    [AccountServiceSegment]         VARCHAR (10)    NULL,
    [DeliveringPlant]               VARCHAR (4)     NULL,
    [PartnerFunction]               VARCHAR (10)    NULL,
    [WharehouseSeqGroup]            VARCHAR (50)    NULL,
    [Incoterm]                      VARCHAR (2)     NULL,
    [IncotermDesc]                  VARCHAR (50)    NULL,
    [FixedIncotermDesc]             VARCHAR (1)     NULL,
    [AogFeeInsideWorkingHours]      VARCHAR (4)     NULL,
    [AogFeeOutsideWorkingHours]     VARCHAR (4)     NULL,
    [AogFeeWeekend]                 VARCHAR (4)     NULL,
    [MarketSegmentCode]             VARCHAR (10)    NULL,
    [HppFlag]                       VARCHAR (1)     NULL,
    [ContractWarehouses]            VARCHAR (MAX)   NULL,
    [SymphonyEnabledFlag]           VARCHAR (1)     NULL,
    [SymphonyDirectShipFlag]        VARCHAR (1)     NULL,
    [LineMinPrefCode]               VARCHAR (1)     NULL,
    [LineMinPrefDesc]               VARCHAR (50)    NULL,
    [OutstandingReceivables]        VARCHAR (50)    NULL,
    [ReceivablesPastDue]            VARCHAR (50)    NULL,
    [ConsolidationFreq]             VARCHAR (1)     NULL,
    [ConsolidationDay]              VARCHAR (25)    NULL,
    [ConsolidationCutoffTime]       VARCHAR (20)    NULL,
    [PackagingSettingEA]            VARCHAR (5)     NULL,
    [PackagingSettingIB]            VARCHAR (5)     NULL,
    [PNdescOnInvoice]               VARCHAR (1)     NULL,
    [POnumberOnInvoice]             VARCHAR (1)     NULL,
    [ManufactureNameOnInvoice]      VARCHAR (1)     NULL,
    [ShowPNonBeCert]                VARCHAR (1)     NULL,
    [ShipLineItemComplete]          VARCHAR (1)     NULL,
    [MinShelfLife]                  VARCHAR (50)    NULL,
    [CurrencyCode]                  VARCHAR (50)    NULL,
    [MarketSegmentCategory]         VARCHAR (255)   NULL,
    [MarketSegmentSubCategory]      VARCHAR (255)   NULL,
    [TestReport]                    VARCHAR (1)     NULL,
    [Dfar]                          VARCHAR (1)     NULL,
    [WarehouseStockGroups]          VARCHAR (MAX)   NULL,
    [AslCustomerFlag]               VARCHAR (1)     NULL,
    [AslCustomerMfrCodes]           VARCHAR (MAX)   NULL,
    [GovernmentAsl]                 VARCHAR (1)     NULL,
    [AslGovernmentMfrCodes]         VARCHAR (50)    NULL,
    [LineMinPriceList]              VARCHAR (3)     NULL,
    [LineMinContracts]              VARCHAR (3)     NULL,
    [BlanketPO]                     VARCHAR (50)    NULL,
    [Spec2000]                      VARCHAR (2)     NULL,
    [MilitaryPartsAllowed]          BIT             NULL,
    [UltimateConsigneeType]         VARCHAR (3)     NULL,
    [CustomerPriority]              VARCHAR (3)     NULL,
    [MinLineValue]                  DECIMAL (18, 2) NULL,
    [ExpediateFeeValue]             DECIMAL (18, 2) NULL,
    [MinOQEnabled]                  BIT             NULL,
    [IOQEnabled]                    BIT             NULL,
    [UltimateConsigneeTypeID]       INT             NULL,
    [CreateDTS]                     DATETIME        NULL,
    [UpdateDTS]                     DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([CustomerAccountID] ASC),
    CONSTRAINT [FK_CustomerAccount_To_CustomerAcctOrg] FOREIGN KEY ([CustomerAccountOrganizationID]) REFERENCES [CDM].[CustomerAccountOrganization] ([CustomerAccountOrganizationID]),
    CONSTRAINT [FK_CustomerAccount_To_SourceSystem] FOREIGN KEY ([SourceSystemID]) REFERENCES [CDM].[SourceSystem] ([SourceSystemID]),
    CONSTRAINT [FK_CustomerAccounts_To_UltimateConsigneeTypeID] FOREIGN KEY ([UltimateConsigneeTypeID]) REFERENCES [CDM].[UltimateConsigneeTypes] ([UltimateConsigneeTypeID])
);

