CREATE TABLE [CDM].[Invoices] (
    [InvoiceID]                 INT             IDENTITY (1, 1) NOT NULL,
    [SourceSystemID]            INT             NULL,
    [EDIMessageCode]            VARCHAR (3)     NULL,
    [OrderAcknowledgeRequired]  BIT             NULL,
    [Currency]                  VARCHAR (3)     NULL,
    [EDICurrency]               VARCHAR (3)     NULL,
    [ExchangeRate]              DECIMAL (18, 4) NULL,
    [TermsOfPayment]            VARCHAR (17)    NULL,
    [VATRegistrationNumber]     VARCHAR (20)    NULL,
    [InvoiceType]               VARCHAR (4)     NULL,
    [InvoiceNumber]             VARCHAR (35)    NULL,
    [NetWeight]                 DECIMAL (18, 2) NULL,
    [WeightUnit]                VARCHAR (3)     NULL,
    [ListType]                  VARCHAR (4)     NULL,
    [UnloadPoint]               VARCHAR (25)    NULL,
    [PurchseOrderNumberSuppl]   VARCHAR (4)     NULL,
    [ShippingConditions]        VARCHAR (2)     NULL,
    [ShippingConditionsDesc]    VARCHAR (20)    NULL,
    [RecipientNumber]           VARCHAR (10)    NULL,
    [OrderCombination]          BIT             NULL,
    [DeliveryComplete]          BIT             NULL,
    [OrderReason]               VARCHAR (3)     NULL,
    [OrderReasonDesc]           VARCHAR (40)    NULL,
    [UsageIndicator]            VARCHAR (3)     NULL,
    [UsageIndicatorDescription] VARCHAR (50)    NULL,
    [BillingCategory]           BIT             NULL,
    [DeliveryBlock]             VARCHAR (2)     NULL,
    [DeliveryBlockDesc]         VARCHAR (20)    NULL,
    [ReceivingPoint]            VARCHAR (25)    NULL,
    [DeptNumber]                VARCHAR (4)     NULL,
    [AgreedDeliveryTime]        DATETIME        NULL,
    [IndirectExchangeRate]      VARCHAR (12)    NULL,
    [CustomerPurchOrder]        VARCHAR (3)     NULL,
    [VendorOrder]               VARCHAR (3)     NULL,
    [DeliveryNoteNumber]        VARCHAR (3)     NULL,
    [ExtDeliveryNoteNumber]     VARCHAR (3)     NULL,
    [RefDocNumberBilling]       VARCHAR (3)     NULL,
    [SupplierDeliveryDate]      DATETIME        NULL,
    [InvoiceCreateDate]         DATETIME        NULL,
    [DocumentDate]              DATETIME        NULL,
    [FixedValueDate]            DATETIME        NULL,
    [BillingDate]               DATETIME        NULL,
    [DueDate]                   DATETIME        NULL,
    [SalesArea]                 VARCHAR (35)    NULL,
    [DeliveryCompanyCode]       VARCHAR (35)    NULL,
    [Division]                  VARCHAR (35)    NULL,
    [DistributionChannel]       VARCHAR (35)    NULL,
    [SalesOrganization]         VARCHAR (35)    NULL,
    [BillingType]               VARCHAR (35)    NULL,
    [SalesDocumentCategory]     VARCHAR (35)    NULL,
    [CreateDTS]                 DATETIME        NULL,
    [UpdateDTS]                 DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([InvoiceID] ASC),
    CONSTRAINT [FK_Invoices_To_SourceSystem] FOREIGN KEY ([SourceSystemID]) REFERENCES [CDM].[SourceSystem] ([SourceSystemID])
);

