CREATE TABLE [CDM].[InvoiceForeignTrade] (
    [InvoiceForeignTradeID]        INT             IDENTITY (1, 1) NOT NULL,
    [InvoiceID]                    INT             NULL,
    [MMSDDocumentCount]            INT             NULL,
    [DepartureCountry]             VARCHAR (3)     NULL,
    [ModeOfTransport]              VARCHAR (1)     NULL,
    [OfficeOfExitEntry]            VARCHAR (6)     NULL,
    [OfficeOfDestination]          VARCHAR (6)     NULL,
    [CustomersOffice1]             VARCHAR (6)     NULL,
    [CustomersOffice2]             VARCHAR (6)     NULL,
    [CustomersOffice3]             VARCHAR (6)     NULL,
    [CustomersOffice4]             VARCHAR (6)     NULL,
    [CustomersOffice5]             VARCHAR (6)     NULL,
    [CustomersOffice6]             VARCHAR (6)     NULL,
    [CrossingBorderMeansInd]       VARCHAR (30)    NULL,
    [DepartureMeansInd]            VARCHAR (30)    NULL,
    [CrossingBorderMeansOrigin]    VARCHAR (3)     NULL,
    [DepartureMeansOrigin]         VARCHAR (3)     NULL,
    [CrossBorderContainer]         BIT             NULL,
    [ForeignTradeCurrency]         VARCHAR (5)     NULL,
    [TotalValueSegment]            DECIMAL (18, 4) NULL,
    [CountryKey]                   VARCHAR (3)     NULL,
    [CountryName]                  VARCHAR (15)    NULL,
    [AltCountryKey]                VARCHAR (3)     NULL,
    [EUMember]                     BIT             NULL,
    [FreeTradeArea]                BIT             NULL,
    [EEAID]                        BIT             NULL,
    [CountryCode5]                 VARCHAR (5)     NULL,
    [CountryCode5JP]               VARCHAR (5)     NULL,
    [CountryOfDispatch]            VARCHAR (15)    NULL,
    [AltCountryKeyDispatch]        VARCHAR (3)     NULL,
    [AltCountryKeyDeparture]       VARCHAR (3)     NULL,
    [AltCountryKeyBorder]          VARCHAR (3)     NULL,
    [AltCountryKeySoldTo]          VARCHAR (3)     NULL,
    [CurrencyByCountry]            VARCHAR (5)     NULL,
    [LoadingPlace]                 VARCHAR (15)    NULL,
    [DomesticModeOfTransport]      BIT             NULL,
    [FTEDI1]                       VARCHAR (16)    NULL,
    [FTEDI2]                       VARCHAR (3)     NULL,
    [CustomsNumber1]               VARCHAR (7)     NULL,
    [CustomsNumber2]               VARCHAR (7)     NULL,
    [CustomsNumber3]               VARCHAR (7)     NULL,
    [CustomsNumber4]               VARCHAR (7)     NULL,
    [CustomsNumber5]               VARCHAR (7)     NULL,
    [CustomsNumber6]               VARCHAR (7)     NULL,
    [FTEDI10]                      VARCHAR (8)     NULL,
    [CustomValuesCurrency]         VARCHAR (5)     NULL,
    [ForeignTradeDescription]      VARCHAR (20)    NULL,
    [ForeignTradeCountryName]      VARCHAR (15)    NULL,
    [CountryName1]                 VARCHAR (15)    NULL,
    [PlaceOfLoadUnload]            VARCHAR (40)    NULL,
    [ForeignTradeProcssingText]    VARCHAR (40)    NULL,
    [TradesProcessingTxt]          VARCHAR (40)    NULL,
    [TradesProcessingTxtLong]      VARCHAR (40)    NULL,
    [CustomsDeclaration]           VARCHAR (20)    NULL,
    [ImportProcessingRegNumber]    VARCHAR (20)    NULL,
    [ImportProcessingExporter]     VARCHAR (10)    NULL,
    [ImportProcessingExporterDesc] VARCHAR (20)    NULL,
    [CustomsCountryOffice]         VARCHAR (3)     NULL,
    [CustomsOfficeCountry1]        VARCHAR (3)     NULL,
    [CustomsOfficeCountry2]        VARCHAR (3)     NULL,
    [CustomsOfficeCountry3]        VARCHAR (3)     NULL,
    [CustomsOfficeCountry4]        VARCHAR (3)     NULL,
    [CustomsOfficeCountry5]        VARCHAR (3)     NULL,
    [CustomsExportOffice]          VARCHAR (6)     NULL,
    [CustomsExportOfficeDesc]      VARCHAR (30)    NULL,
    [MeansOfTransport]             VARCHAR (6)     NULL,
    [Association]                  BIT             NULL,
    [CustomsDeclarationType]       VARCHAR (3)     NULL,
    [DateServiceUpdate]            BIT             NULL,
    [CreateDTS]                    DATETIME        NULL,
    [UpdateDTS]                    DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([InvoiceForeignTradeID] ASC),
    CONSTRAINT [FK_InvoiceForeignTrade_To_Invoices] FOREIGN KEY ([InvoiceID]) REFERENCES [CDM].[Invoices] ([InvoiceID])
);

