CREATE TABLE [CDM].[InvoiceItems] (
    [InvoiceItemID]            INT             IDENTITY (1, 1) NOT NULL,
    [InvoiceNumber]            VARCHAR (10)    NULL,
    [InvoiceID]                INT             NULL,
    [ActionCode]               VARCHAR (3)     NULL,
    [ItemCategory]             VARCHAR (1)     NULL,
    [OrderAcknowledgeRequired] BIT             NULL,
    [Quantity]                 INT             NULL,
    [UOM]                      VARCHAR (3)     NULL,
    [QtyInPriceUnit]           INT             NULL,
    [PriceUOM]                 VARCHAR (3)     NULL,
    [CumulativeQty]            INT             NULL,
    [NetPrice]                 DECIMAL (10, 2) NULL,
    [UnitPrice]                DECIMAL (10, 2) NULL,
    [InvoiceItemValue]         DECIMAL (18, 2) NULL,
    [AbsoluteValue]            DECIMAL (18, 2) NULL,
    [QualifyCashAmt]           DECIMAL (18, 2) NULL,
    [NetWeight]                DECIMAL (18, 2) NULL,
    [WeightUnit]               VARCHAR (3)     NULL,
    [ScheduleLine]             BIT             NULL,
    [Currency]                 VARCHAR (3)     NULL,
    [GrossPrice]               DECIMAL (18, 5) NULL,
    [MaterialClass]            VARCHAR (9)     NULL,
    [BOMLevelItem]             VARCHAR (6)     NULL,
    [DeliveryGroupDelivered]   VARCHAR (3)     NULL,
    [ShippingInstructions]     VARCHAR (10)    NULL,
    [ConvDenominator]          VARCHAR (6)     NULL,
    [ConvNumerator]            VARCHAR (6)     NULL,
    [RejectionReason]          VARCHAR (2)     NULL,
    [Description]              VARCHAR (40)    NULL,
    [MaxNumOfDeliveries]       INT             NULL,
    [QtyFixed]                 BIT             NULL,
    [OrderCombination]         BIT             NULL,
    [TotalWeight]              DECIMAL (18, 5) NULL,
    [SalesItemCategory]        VARCHAR (4)     NULL,
    [ReceivingPoint]           VARCHAR (25)    NULL,
    [DeptNumber]               VARCHAR (4)     NULL,
    [UsageIndicator]           VARCHAR (3)     NULL,
    [PlantID]                  INT             NULL,
    [DeliveryPriority]         VARCHAR (2)     NULL,
    [DeliveryDesc]             VARCHAR (50)    NULL,
    [DeliveryRoute]            VARCHAR (6)     NULL,
    [RouteDescription]         VARCHAR (50)    NULL,
    [StorageLocation]          VARCHAR (4)     NULL,
    [ShipReceivePoint]         VARCHAR (4)     NULL,
    [DeliveryTime]             DATETIME        NULL,
    [ProductID]                INT             NULL,
    [AddlValueDays]            INT             NULL,
    [SuperiorItem]             VARCHAR (6)     NULL,
    [Hierarchy]                BIT             NULL,
    [ATPEncrypt]               VARCHAR (25)    NULL,
    [MaterialNumberEXT]        VARCHAR (40)    NULL,
    [IUIDRelevant]             BIT             NULL,
    [ListPrice]                DECIMAL (18, 2) NULL,
    [ListDiscount]             DECIMAL (18, 2) NULL,
    [ActualFreight]            DECIMAL (18, 2) NULL,
    [SalesOrderDate]           DATETIME        NULL,
    [SupplierDeliveryDate]     DATETIME        NULL,
    [IDOCCreateDate]           DATETIME        NULL,
    [InvoiceCreateDate]        DATETIME        NULL,
    [ServicesRenderedDate]     DATETIME        NULL,
    [PricingDate]              DATETIME        NULL,
    [CustomerOrder]            VARCHAR (35)    NULL,
    [VendorOrder]              VARCHAR (35)    NULL,
    [PrecedingNoteNumber]      VARCHAR (35)    NULL,
    [CreateDTS]                DATETIME        NULL,
    [UpdateDTS]                DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([InvoiceItemID] ASC),
    CONSTRAINT [FK_InvoiceItems_To_Invoice] FOREIGN KEY ([InvoiceID]) REFERENCES [CDM].[Invoices] ([InvoiceID])
);

