CREATE TABLE [CDM].[OrderItems] (
    [OrderItemsID]            INT             NULL,
    [OrderID]                 INT             NULL,
    [OrderItemCK]             VARCHAR (10)    NULL,
    [RejectionReason]         VARCHAR (255)   NULL,
    [RejectionState]          VARCHAR (3)     NULL,
    [SoldTo]                  INT             NULL,
    [ShipTo]                  INT             NULL,
    [ReferenceDocNumber]      VARCHAR (12)    NULL,
    [QuoteItemNumber]         VARCHAR (12)    NULL,
    [XPSRoute]                VARCHAR (10)    NULL,
    [OrderType]               VARCHAR (5)     NULL,
    [DocumentCurrency]        VARCHAR (3)     NULL,
    [TermsOfPayment]          VARCHAR (5)     NULL,
    [ShippingPaymentMethod]   VARCHAR (3)     NULL,
    [ProductID]               INT             NULL,
    [OrderQty]                INT             NULL,
    [SalesOrderItemTXT]       VARCHAR (255)   NULL,
    [TargetQty]               INT             NULL,
    [PlantID]                 INT             NULL,
    [BaseUOM]                 VARCHAR (5)     NULL,
    [SalesUOM]                VARCHAR (5)     NULL,
    [SubstitutionReason]      VARCHAR (20)    NULL,
    [PartialDelivery]         BIT             NULL,
    [NetValue]                DECIMAL (18, 2) NULL,
    [NetPrice]                DECIMAL (18, 2) NULL,
    [ExtendedPrice]           DECIMAL (18, 2) NULL,
    [Priority]                VARCHAR (15)    NULL,
    [DeliveryScheduleLineNbr] VARCHAR (5)     NULL,
    [Include8130]             BIT             NULL,
    [IncludeFAA]              BIT             NULL,
    [ShelfLifePct]            DECIMAL (10, 2) NULL,
    [CertsFlag]               BIT             NULL,
    [TestReportFlag]          BIT             NULL,
    [DFARFlag]                BIT             NULL,
    [Tag8130]                 BIT             NULL,
    [TSO]                     BIT             NULL,
    [PMA]                     BIT             NULL,
    [Charge8130Fee]           BIT             NULL,
    [AOGService]              BIT             NULL,
    [AOGTailNumber]           VARCHAR (10)    NULL,
    [ASLFlag]                 BIT             NULL,
    [ConfirmedQtySchLine]     DECIMAL (18, 4) NULL,
    [ScheduleLineDate]        DATETIME        NULL,
    [GoodIssueDate]           DATETIME        NULL,
    [MaterialAvailDate]       DATETIME        NULL,
    [UnloadPoint]             VARCHAR (30)    NULL,
    [IsHazmat]                BIT             NULL,
    [IsDryIceReq]             BIT             NULL,
    [IsOverSized]             BIT             NULL,
    [CreateDTS]               DATETIME        NULL,
    [UpdateDTS]               DATETIME        NULL,
    CONSTRAINT [FK_OrderItems_To_Orders] FOREIGN KEY ([OrderID]) REFERENCES [CDM].[Orders] ([OrderID]),
    CONSTRAINT [FK_OrderItems_To_Products] FOREIGN KEY ([ProductID]) REFERENCES [CDM].[Products] ([ProductID])
);

