CREATE TABLE [CDM].[Orders] (
    [OrderID]            INT             IDENTITY (1, 1) NOT NULL,
    [OrderNumberCK]      VARCHAR (50)    NULL,
    [SourceSystemID]     INT             NULL,
    [SourceSystemName]   VARCHAR (10)    NULL,
    [OverallStatus]      VARCHAR (2)     NULL,
    [PONumber]           VARCHAR (40)    NULL,
    [PaymentPlanNumber]  VARCHAR (12)    NULL,
    [CurrentDate]        DATETIME        NULL,
    [DeliveryBlock]      VARCHAR (3)     NULL,
    [SDDocumentCategory] VARCHAR (3)     NULL,
    [CompanyCode]        VARCHAR (5)     NULL,
    [OrderReason]        VARCHAR (255)   NULL,
    [ShipToPreference]   VARCHAR (20)    NULL,
    [BlockStatus]        VARCHAR (2)     NULL,
    [CreditCheckStatus]  VARCHAR (2)     NULL,
    [OrderMinFee]        DECIMAL (18, 2) NULL,
    [Tag8130Fee]         DECIMAL (18, 2) NULL,
    [AOGServiceFee]      DECIMAL (18, 2) NULL,
    [HazmatFee]          DECIMAL (18, 2) NULL,
    [TotalPrice]         DECIMAL (18, 2) NULL,
    [TotalQuantity]      DECIMAL (18, 2) NULL,
    [ModifiedDate]       DATETIME        NULL,
    [DotComUserName]     VARCHAR (50)    NULL,
    [DotComUser]         VARCHAR (100)   NULL,
    [OrderDate]          DATETIME        NULL,
    [DocumentCreatedOn]  DATETIME        NULL,
    [ValidToDate]        DATETIME        NULL,
    [InsertSource]       VARCHAR (3)     NULL,
    [InsertDate]         DATETIME        NULL,
    [CustomerAccountID]  INT             NULL,
    [ContactPointID]     INT             NULL,
    [CreateDTS]          DATETIME        NULL,
    [UpdateDTS]          DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([OrderID] ASC),
    CONSTRAINT [FK_Orders_To_ContactPoint] FOREIGN KEY ([ContactPointID]) REFERENCES [CDM].[ContactPoints] ([ContactPointID]),
    CONSTRAINT [FK_Orders_To_Customers] FOREIGN KEY ([CustomerAccountID]) REFERENCES [CDM].[CustomerAccounts] ([CustomerAccountID])
);

