CREATE TABLE [CDM].[Partners] (
    [PartnerID]                     INT          IDENTITY (1, 1) NOT NULL,
    [SourceSystemID]                INT          NULL,
    [PartnerNumber]                 VARCHAR (17) NULL,
    [VendorNumberCustomerLocation]  VARCHAR (17) NULL,
    [PartnerName1]                  VARCHAR (35) NULL,
    [PartnerName2]                  VARCHAR (35) NULL,
    [PartnerName3]                  VARCHAR (35) NULL,
    [PartnerName4]                  VARCHAR (35) NULL,
    [PartnerStreetHouse1]           VARCHAR (35) NULL,
    [PartnerStreetHouse2]           VARCHAR (35) NULL,
    [PartnerPOBox]                  VARCHAR (35) NULL,
    [PartnerCity]                   VARCHAR (35) NULL,
    [PartnerCountyCode]             VARCHAR (9)  NULL,
    [PartnerPostalCode]             VARCHAR (9)  NULL,
    [PartnerPOPostalCode]           VARCHAR (9)  NULL,
    [PartnerCountryKey]             VARCHAR (3)  NULL,
    [PartnerUnloadingPoint]         VARCHAR (35) NULL,
    [PartnerContactPersonnelNumber] VARCHAR (30) NULL,
    [PartnerContactPersonNumber]    VARCHAR (30) NULL,
    [Partner1stTelephone]           VARCHAR (25) NULL,
    [Partner2ndTelephone]           VARCHAR (25) NULL,
    [PartnerTeleboxNumber]          VARCHAR (25) NULL,
    [PartnerFaxNumber]              VARCHAR (25) NULL,
    [PartnerTeletexNumber]          VARCHAR (25) NULL,
    [PartnerTelexNumber]            VARCHAR (25) NULL,
    [PartnerLanguageKey]            VARCHAR (1)  NULL,
    [PartnerFormOf]                 VARCHAR (15) NULL,
    [PartnerDistrict]               VARCHAR (35) NULL,
    [PartnerHouseNumber]            VARCHAR (6)  NULL,
    [PartnerFloor]                  VARCHAR (6)  NULL,
    [PartnerRegion]                 VARCHAR (3)  NULL,
    [PartnerGender]                 VARCHAR (1)  NULL,
    [PartnerCountryIso]             VARCHAR (2)  NULL,
    [PartnerCompanyKeyFrance]       VARCHAR (20) NULL,
    [PartnerYourReference]          VARCHAR (30) NULL,
    [PartnerContactUserName]        VARCHAR (35) NULL,
    [PartnerOrgCode]                VARCHAR (30) NULL,
    [PartnerOrgDescription]         VARCHAR (35) NULL,
    [PartnerGroupCode]              VARCHAR (30) NULL,
    [PartnerCustomerDescription]    VARCHAR (30) NULL,
    [PartnerCharacterField]         VARCHAR (70) NULL,
    [PartnerPOBoxCity]              VARCHAR (35) NULL,
    [LanguageAccordingISO639]       VARCHAR (2)  NULL,
    [PartnerTitle]                  VARCHAR (15) NULL,
    [CreateDTS]                     DATETIME     NULL,
    [UpdateDTS]                     DATETIME     NULL,
    PRIMARY KEY CLUSTERED ([PartnerID] ASC)
);

